{% set name = "qtypes" %}
{% set version = "2023.3.0" %}


package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.org/packages/source/{{ name[0] }}/{{ name }}/qtypes-{{ version }}.tar.gz
  sha256: f4ef997f1c82396a95d14e91aa95fbcd17cfef7e4bc70727e73f03bc801ac041

build:
  number: 1
  noarch: python
  script: {{ PYTHON }} -m pip install . -vv --no-deps --no-build-isolation

requirements:
  host:
    - python {{ python_min }}
    - flit
    - pyside2
    - qtpy
    - pip
    - pint
  run:
    - python >={{ python_min }}
    - qtpy
    - pint
  run_constrained:
    - pyside2 >=5.12
    - pyqt >=5

test:
  imports:
    - qtypes
  commands:
    - pip check
  requires:
    - pip
    - pyside2
    - python {{ python_min }}

about:
  home: https://gitlab.com/yaq/qtypes
  summary: Build qt graphical user interfaces out of simple type objects.
  dev_url: https://gitlab.com/yaq/qtypes
  license: LGPL-3.0-only
  license_file: LICENSE

extra:
  recipe-maintainers:
    - untzag
    - ksunden
    - darienmorrow
    - kameyer226
    - ddkohler
