{% set name = "qtypes" %}
{% set version = "2022.6.0" %}


package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/qtypes-{{ version }}.tar.gz
  sha256: 55de86f090391b45cba9af53acbaa59272a20270165f5b19eee87f2174dd68eb

build:
  number: 0
  noarch: python
  script: {{ PYTHON }} -m pip install . -vv --no-build-isolation

requirements:
  host:
    - python >=3.8
    - flit
    - pyside2
    - qtpy
    - pip
    - pint
  run:
    - python >=3.8
    - qtpy
    - pint
  run_constrained:
    - pyside2 >=5.12
    - pyqt >=5

test:
  imports:
    - qtypes
  commands:
    - pip check
  requires:
    - pip
    - pyside2

about:
  home: https://gitlab.com/yaq/qtypes
  summary: Build qt graphical user interfaces out of simple type objects.
  dev_url: https://gitlab.com/yaq/qtypes
  license: LGPL-3.0-only
  license_file: LICENSE

extra:
  recipe-maintainers:
    - untzag
    - ksunden
    - darienmorrow
    - kameyer226
    - ddkohler
